version: "3.8"

services:
  dev:
    container_name: canary_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # default user is "opam"
      - ..:/workspace:cached
      - opam:/home/opam/.opam:cached
      - build:/workspace/_build:cached
      - ${HOME}${USERPROFILE:-}/.ssh:/home/opam/.ssh
      - ${HOME}${USERPROFILE:-}/.gitconfig:/home/opam/.gitconfig
      - ${HOME}${USERPROFILE:-}/.gitignore_global:/home/opam/.gitignore_global
    command: sleep infinity

volumes:
  opam:
  build:
